#------------------------------------------------------------------------------#
# Application YAML #
# inside ./src/main/resources/application.yml
#------------------------------------------------------------------------------#
debug: false

spring:
  ## Thymeleaf configuration:
  thymeleaf:
    cache: false
    mode: HTML

  ## H2 Servlet setting
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /admin/h2

  datasource:
    url: jdbc:h2:mem:dataSource;MODE=LEGACY;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password:
  
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
  
  sql:
    init:
      continue-on-error: true

logging:
  level:
    org:
      thymeleaf:
        extras:
          springsecurity6:
            auth: TRACE
      springframework:
        security:
          acls: TRACE