#------------------------------------------------------------------------------#
# Application YAML #
# inside ./src/main/resources/application.yml
#------------------------------------------------------------------------------#

spring:
  ## Thymeleaf configuration:
  thymeleaf:
    cache: false
    mode: HTML5
  resources:
    cache-period: 0

##---------------------------------------------------------------------------##
