# Application properties that need to be
# embedded within the web application can be included here
server:
  port: 9443
  ssl:
    key-store: classpath:/etc/cas/thekeystore
    key-store-password: changeit


cas:
  service-registry:
    core:
      init-from-json: true
    json:
      location: classpath:/etc/cas/services